# Generated by Django 6.0.3 on 2026-03-17 04:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='temple',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.temple'),
            preserve_default=False,
        ),
    ]
