# Generated by Django 5.2.9 on 2026-03-17 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_booking_id_alter_pooja_id_alter_temple_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='gotra',
        ),
        migrations.AlterField(
            model_name='booking',
            name='nakshatra',
            field=models.CharField(default='General', max_length=100),
        ),
    ]
