# Generated by Django 5.2.9 on 2026-03-17 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_remove_booking_gotra_alter_booking_nakshatra'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='nakshatra',
            field=models.CharField(max_length=100),
        ),
    ]
